In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('data/Life Expectancy Data 1.csv')
df2 = pd.read_csv('data/Life Expectancy Data 2.csv')
df3 = pd.read_csv('data/bmi_and_life_expectancy.csv')

In [24]:
df.head()

,Country,Year,Status,Life expectancy,Adult Mortality,infant deaths,Alcohol,percentage expenditure,Hepatitis B,Measles,...,Polio,Total expenditure,Diphtheria,HIV/AIDS,GDP,Population,thinness 1-19 years,thinness 5-9 years,Income composition of resources,Schooling
0,Afghanistan,2015,Developing,65.0,263.0,62,0.01,71.279624,65.0,1154,...,6.0,8.16,65.0,0.1,584.259210,33736494.0,17.2,17.3,0.479,10.1
1,Afghanistan,2014,Developing,59.9,271.0,64,0.01,73.523582,62.0,492,...,58.0,8.18,62.0,0.1,612.696514,327582.0,17.5,17.5,0.476,10.0
2,Afghanistan,2013,Developing,59.9,268.0,66,0.01,73.219243,64.0,430,...,62.0,8.13,64.0,0.1,631.744976,31731688.0,17.7,17.7,0.470,9.9
3,Afghanistan,2012,Developing,59.5,272.0,69,0.01,78.184215,67.0,2787,...,67.0,8.52,67.0,0.1,669.959000,3696958.0,17.9,18.0,0.463,9.8
4,Afghanistan,2011,Developing,59.2,275.0,71,0.01,7.097109,68.0,3013,...,68.0,7.87,68.0,0.1,63.537231,2978599.0,18.2,18.2,0.454,9.5

In [25]:
df.groupby(['Status']).count()

,Country,Year,Life expectancy,Adult Mortality,infant deaths,Alcohol,percentage expenditure,Hepatitis B,Measles,BMI,...,Polio,Total expenditure,Diphtheria,HIV/AIDS,GDP,Population,thinness 1-19 years,thinness 5-9 years,Income composition of resources,Schooling
Status,,,,,,,,,,,,,,,,,,,,,
Developed,512,512,512,512,512,484,512,339,512,512,...,512,480,512,512,448,416,512,512,464,464
Developing,2426,2426,2416,2416,2426,2260,2426,2046,2426,2392,...,2407,2232,2407,2426,2042,1870,2392,2392,2307,2311

In [3]:
df = df.rename(columns={'Life expectancy ':'Life_Expectancy','Adult Mortality':'Adult_Mortality',
                   'infant deaths':'Infant_Deaths', 'percentage expenditure':'percentage_expenditure',
                  'Hepatitis B':'Hepatitis_B','Measles ':'Measles',' BMI ':'BMI',
                    'under-five deaths ':'under_five_deaths',' HIV/AIDS':'HIV_AIDS',
                  'Total expenditure':'Total_expenditure',' thinness  1-19 years':'thinness_1to19_years',
                  ' thinness 5-9 years':'thinness_5to9_years','Diphtheria ':'Diphtheria',
                  'Income composition of resources':'Income_composition_of_resources'})

In [5]:
df.count()

Country                            2938
Year                               2938
Status                             2938
Life_Expectancy                    2928
Adult_Mortality                    2928
Infant_Deaths                      2938
Alcohol                            2744
percentage_expenditure             2938
Hepatitis_B                        2385
Measles                            2938
BMI                                2904
under_five_deaths                  2938
Polio                              2919
Total_expenditure                  2712
Diphtheria                         2919
HIV_AIDS                           2938
GDP                                2490
Population                         2286
thinness_1to19_years               2904
thinness_5to9_years                2904
Income_composition_of_resources    2771
Schooling                          2775
dtype: int64

In [4]:
df = df[np.isfinite(df['Life_Expectancy'])]
df = df[np.isfinite(df['BMI'])]
# df = df[np.isfinite(df['Income_composition_of_resources'])]
# df = df[np.isfinite(df['GDP'])]
df.count()

Country                            2896
Year                               2896
Status                             2896
Life_Expectancy                    2896
Adult_Mortality                    2896
Infant_Deaths                      2896
Alcohol                            2720
percentage_expenditure             2896
Hepatitis_B                        2363
Measles                            2896
BMI                                2896
under_five_deaths                  2896
Polio                              2888
Total_expenditure                  2684
Diphtheria                         2888
HIV_AIDS                           2896
GDP                                2461
Population                         2252
thinness_1to19_years               2896
thinness_5to9_years                2896
Income_composition_of_resources    2736
Schooling                          2736
dtype: int64

In [5]:
df.to_csv('clean_data.csv')